name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Get code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install GNU Octave
      run: |
        sudo apt-get update && sudo apt-get install -y cmake octave octave-dev && \
        octave --version

    - name: Compile MEX file
      run: make MEXBIN="mkoctfile --mex" MEXEXT=mex

    - name: Install whisper.m in GNU Octave
      run: octave --no-gui --no-window-system --silent --eval "addpath (pwd); savepath ();"

    - name: Run whisper.m demo
      run: octave --no-gui --no-window-system --silent --eval "try, whisper.demo (); exit (0); catch, exit (1); end_try_catch"
